title: "Sanya Syed — Data Engineer & Analyst"
description: "Continuously learning, engineering, and delivering data solutions that matter"
theme: jekyll-theme-minimal
author: "Sanya Syed"
github_username: "SanyaSSyed"